local M = {
    personal = {
        username = 'chiddy',
        email = 'chiddy@chiddy.xyz',
        github = 'chidddy',
    },
    urls = {
        protocol = 'https://',
        github = 'github.com',
        twitter = 'twitter.com',
        personal = 'chiddy.xyz',
    },
    home = '/home/chiddy',
    projects = '/projects',
    locals = '/projects/lua/nvim/',
    palette = 'catppuccin',
    theme = 'basic',
    lsp = {
        servers = {
            system = {
                'clangd',
                'lua_ls',
            },
            installer = {
                'bashls',
                'cmake',
                'rust_analyzer',
                'gopls',
                'tsserver',
                'typst_lsp',
                'yamlls',
                'lemminx',
                'html',
                'jsonls',
                'taplo',
            },
        },
        format_on_save = true,
    },
    dap = {
        adapters = {
            'cppdbg',
            'codelldb',
        },
        configs = {},
    },
    dashboard_hide_cursor = true,
    ft = {
        quick_close = {
            'OverseerList',
            'PlenaryTestPopup',
            'Trouble',
            'help',
            'lspinfo',
            'man',
            'neotest-output',
            'neotest-output-panel',
            'neotest-summary',
            'noice',
            'notify',
            'qf',
            'spectre_panel',
            'startuptime',
            'tsplayground',
        },
        dashboard = {
            'Alpha',
            'Dashboard',
            'Mason',
            'alpha',
            'dashboard',
            'lazy',
        },
        disable_visuals = {
            'Alpha',
            'Mason',
            'NvimTree',
            'Outline',
            'TelescopePrompt',
            'Trouble',
            'alpha',
            'dashboard',
            'fugitive',
            'lazy',
            'neo-tree',
            'noice',
        },
    },
    bt = {
        disable_visuals = {
            'checkhealth',
            'help',
            'nofile',
            'prompt',
            'quickfix',
        },
    },
}

return M
