---@class icons
local icons = {
    git = {
        add = '',
        change = '',
        remove = '',
        ignore = '',
        rename = '',
        unstage = '',
        unstage_alt = '',
        stage = '',
        stage_alt = '',
        branch = '󰘬',
        diff = '',
        repo = '',
        ahead = '⇡',
        behind = '⇣',
    },
    chevron = {
        up = '',
        down = '',
        left = '',
        right = '',
        thin = {
            up = '',
            down = '',
            left = '',
            right = '',
        },
        double = {
            up = '󰄿',
            down = '',
            left = '󰄽',
            right = '󰄾',
        },
    },
    -- TODO: finish new DAP icons
    dap = {
        points = {
            breakpoint = 'ß',
            condition = 'ﳁ',
            rejected = '',
            log = '',
        },
        pause = '',
        play = '',
        quit = 'ﱢ',
        run_last = '↻',
        stopped = '',
        step = {
            into = '',
            back = '',
            out = '',
            over = '',
        },
    },
    diag = {
        error = '',
        warn = '',
        info = '',
        hint = '',
        other = '',
        hollow = {
            error = '',
            warn = '',
            info = '',
            hint = '',
            other = '',
        },
    },
    kind = {
        -- Class = "",
        -- Class = 'ﴯ',
        Class = '',
        Color = '',
        Constant = '',
        -- Constructor = "",
        Constructor = '',
        Enum = '',
        EnumMember = '',
        Event = '',
        Field = '',
        File = '',
        Folder = '',
        Function = '',
        Interface = '',
        -- Keyword = "",
        Keyword = '',
        Method = '',
        -- Module = '',
        Module = '',
        Namespace = '',
        Number = '#',
        Operator = '',
        -- Package = '',
        Package = '',
        Property = 'ﰠ',
        Reference = '',
        -- Snippet = '',
        Snippet = '',
        Struct = '',
        Text = '',
        TypeParameter = '',
        Unit = '',
        Value = '',
        Variable = '',
        -- ccls-specific icons.
        TypeAlias = '',
        Parameter = '',
        StaticMethod = '',
        Macro = '',
    },
    sep = {
        left = {
            arrow = '',
            rounded = '',
            slant = '',
            slant_top = '',
        },
        right = {
            arrow = '',
            rounded = '',
            slant = '',
            slant_top = '',
        },
        bar = {
            thick = '█',
            normal = '┃',
            thin = '│',
            left = {
                arrow = '',
                rounded = '',
                slant = '',
                slant_top = '',
            },
            right = {
                arrow = '',
                rounded = '',
                slant = '',
                slant_top = '',
            },
        },
    },
    ui = {
        documents = {
            file = '',
            file_alt = '',
            bookmark = '',
            project = '󰂺',
            project_alt = '󰭤',
            repo = '',
            folder = {
                open = {
                    full = '',
                    empty = '',
                },
                closed = {
                    full = '',
                    empty = '',
                },
            },
            symlink = {
                file = '',
                folder = '',
            },
        },
        controls = {
            search = {
                text = '',
                file = '',
            },
            signin = '',
            signout = '',
            sort = {
                letters = {
                    asc = '󰖽',
                    desc = '󰖿',
                },
                size = {
                    asc = '󰒼',
                    desc = '󰒽',
                },
                number = {
                    asc = '󱎉',
                    desc = '󱎊',
                },
            },
            spell = '󰓆',
        },
        cross = '',
        plus = '',
        check = '',
        cross_alt = '',
        plus_alt = '',
        check_alt = '',
        table = '',
        truncate = '…',
        trash = 'ﮁ',
        download = '',
        comment = '',
        list = '',
        lock = '',
        note = '',
    },
    misc = {
        arrow = {
            left = {
                circle = '',
                square = '󰜲',
                normal = '󰜱',
                hollow = {
                    circle = '',
                    square = '󰜳',
                    normal = '󰧀',
                },
            },
            right = {
                circle = '',
                square = '󰜵',
                normal = '󰜴',
                hollow = {
                    circle = '',
                    square = '󰜶',
                    normal = '󰧂',
                },
            },
            up = {
                circle = '',
                square = '󰜸',
                normal = '󰜷',
                hollow = {
                    circle = '',
                    square = '󰜹',
                    normal = '󰧇',
                },
            },
            down = {
                circle = '',
                square = '󰜯',
                normal = '󰜮',
                hollow = {
                    circle = '',
                    square = '󰜰',
                    normal = '󰦿',
                },
            },
        },
        light = {
            on = 'ﯦ',
            off = '',
            hollow = {
                on = 'ﯧ',
                off = '',
            },
        },
        bracket = {
            right = '❯',
            left = '❮',
        },
        lock = '',
        package = '',
        calendar = '',
        pencil = '',
        telescope = '',
        clock = '',
        document = '',
        bell = {
            normal = '󰂚',
            cross = '󰂛',
            hollow = {
                normal = '󰂜',
                cross = '󰪑',
            },
        },
        wind = '',
        emoji = '',
        fire = '',
        gear = '',
        circle = {
            filled = '',
            empty = '',
            dot = '•',
            dot_outline = '',
        },
        bug = '',
        campass = '',
        code = '',
        gavel = '',
        glass = '',
        plugins = '',
        tag = '',
        terminal = '',
        tree = '',
        vim = '',
        ghost = '',
        person = '',
        slash = '',
    },
    borders = {
        dash_rounded = {
            chars = { '┄', '┊', '┄', '┊', '╭', '╮', '╯', '╰' },
            horizontal = '┄',
            vertical = '┊',
        },
        dash = {
            chars = { '┄', '┊', '┄', '┊', '┌', '┐', '┘', '└' },
            horizontal = '┄',
            vertical = '┊',
        },
        single = {
            chars = { '─', '│', '─', '│', '┌', '┐', '┘', '└' },
            horizontal = '─',
            vertical = '│',
        },
        double = {
            chars = { '═', '║', '═', '║', '╔', '╗', '╝', '╚' },
            horizontal = '═',
            vertical = '║',
        },
        rounded = {
            chars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰' },
            horizontal = '─',
            vertical = '│',
        },
    },
}
return icons
