return {
    require('chiddy.plugins.editor.autopair'),
    require('chiddy.plugins.editor.comment'),
    require('chiddy.plugins.editor.dial'),
    require('chiddy.plugins.editor.minimove'),
    require('chiddy.plugins.editor.neogen'),
    require('chiddy.plugins.editor.rename'),
    require('chiddy.plugins.editor.ssr'),
    require('chiddy.plugins.editor.surround'),
    require('chiddy.plugins.editor.tabout'),
    require('chiddy.plugins.editor.template-string'),
    require('chiddy.plugins.editor.ultimate-autopair'),
    require('chiddy.plugins.editor.ufo'),
    require('chiddy.plugins.editor.yanky'),
}
