-- TODO: cull plugins and find replacements for some
--       - projects
--       - runners
--       - tests
--       - todo-comments
-- TODO: finish LSP and DAP
-- TODO: FIX NEODEV/NEOCONF
-- TODO: finish chiddy.ui
--       - restructure alpha and heirline components
--       - try out nougat
require('chiddy.core')
