-- TODO: cull plugins and find replacements for some
--       - git
--       - projects
--       - runners
--       - tests
--       - todo-comments
-- TODO: better organize plugin categories (split editor into sub categories)
-- TODO: finish LSP and DAP
-- TODO: FIX NEODEV/NEOCONF
-- TODO: finish chiddy.themes
--       - restructure alpha and heirline configs
--       - restructure statusline components
require('chiddy.core')
